// «БЕЛЕС» matnlari — modul o'z lug'ati bilan yuradi.
//
// Nima uchun messages/uz.json va messages/kk.json ga TEGILMADI: modul
// butunlay qo'shimcha qatlam bo'lib qolishi kerak. Kelajakda `lib/beles`,
// `app/[locale]/beles`, `components/beles` papkalarini o'chirsangiz —
// mavjud tarjima fayllarida hech qanday "osilib qolgan" kalit qolmaydi.

export type BelesLocale = 'uz' | 'kk';

const uz = {
  title: 'Белес',
  subtitle: 'Kitobxonlik o‘yini',

  // Holat sahifasi
  yourProgress: 'Sizning holatingiz',
  currentPage: 'Joriy bet',
  currentKey: 'Kalit',
  totalScore: 'Umumiy ball',
  level: 'Daraja',
  letters: 'Yig‘ilgan harflar',
  noLetters: 'Hali harf yig‘ilmagan',
  sessions: 'Seanslar',
  book: 'Kitob',
  noBook: 'Kitob hali biriktirilmagan',
  startSession: 'Seansni boshlash',
  continueSession: 'Seansni davom ettirish',
  todayDone: 'Bugungi seans yakunlandi. Ertaga kutamiz!',
  todayScore: 'Bugungi ball',

  // Kunlik kod
  codeTitle: 'Kunlik kod',
  codeHint: 'Kutubxonachidan bugungi 4 xonali kodni so‘rang',
  codePlaceholder: '0000',
  start: 'Boshlash',

  // O‘qish
  reading: 'O‘qish vaqti',
  readingHint:
    'Telefonni qo‘ying va kitob o‘qing. Vaqt serverda hisoblanadi — ekran o‘chsa ham to‘xtamaydi.',
  warnFive: '5 daqiqa qoldi',
  extend: '+15 daqiqa',
  extendHint: 'Qo‘shimcha vaqt ballni kamaytirmaydi',
  readingOver: 'O‘qish vaqti tugadi',
  pageLabel: 'Nechanchi betda to‘xtadingiz?',
  pagePlaceholder: 'Bet raqami',
  toQuestions: 'Savollarga o‘tish',

  // Javoblar
  answering: 'Javob vaqti',
  extraTime: '+3 daqiqa',
  extraTimeHint: 'Faqat bir marta beriladi',
  extraTimeUsed: 'Qo‘shimcha vaqt ishlatilgan',
  attemptsLeft: 'Urinish qoldi',
  answer: 'Javob berish',
  answerPlaceholder: 'Javobingizni yozing',
  orderHint: 'Variantlarni to‘g‘ri tartibda bosing',
  clear: 'Tozalash',
  correct: 'To‘g‘ri!',
  wrong: 'Noto‘g‘ri',
  hint: 'Ipucha',
  solved: 'Yechildi',
  closed: 'Yopildi',
  points: 'ball',
  newLetter: 'Yangi harf',
  noQuestions: 'Bu betgacha savol qolmadi. Seans qatnashish bali bilan yakunlandi.',

  // Yakun
  finished: 'Seans yakunlandi',
  expired: 'Javob vaqti tugadi',
  sessionScore: 'Seans bali',
  backHome: '«Белес» sahifasiga qaytish',
  back: 'Orqaga',
  toLibrary: 'Kutubxona',
  loading: 'Yuklanmoqda…',

  // Xodim panellari
  librarianPanel: 'Kutubxonachi paneli',
  teacherPanel: 'O‘qituvchi paneli',
  dailyCodeTitle: 'Bugungi kod',
  generateCode: 'Kod yaratish',
  codeReady: 'O‘quvchilarga shu kodni ayting',
  noCodeYet: 'Bugun uchun kod hali yaratilmagan',
  attendance: 'Bugungi davomat',
  noSessions: 'Bugun hali hech kim seans boshlamadi',
  refresh: 'Yangilash',
  participants: 'Ishtirokchilar',
  noParticipants: 'Ishtirokchi yo‘q',
  statTotal: 'Jami ishtirokchi',
  statToday: 'Bugungi seanslar',
  statReading: 'O‘qimoqda',
  statAnswering: 'Javob bermoqda',
  deepAnswers: 'Chuqur javoblar',
  noDeepAnswers: 'Baholanadigan javob yo‘q',
  gradeBtn: 'Baholash',
  gradedLabel: 'Baholangan',
  scorePlaceholder: 'Ball (0–100)',
  finalConfirm: 'Yakuniy tasdiq',
  confirmBtn: 'Tasdiqlash',
  certificate: 'Sertifikat',
  verifyCode: 'Tekshiruv kodi',
  keysDone: 'Ochilgan kalitlar',
  colName: 'Ism',
  colClass: 'Sinf',
  colGroup: 'Guruh',
  colStatus: 'Holat',
  colPage: 'Bet',
  colScore: 'Ball',
  colTime: 'Vaqt',
  colKey: 'Kalit',
  colSessions: 'Seanslar',
  colLevel: 'Daraja',
  colBook: 'Kitob',
  colActions: 'Amal',
  phases: {
    reading: 'O‘qimoqda',
    reading_over: 'Bet raqamini kutmoqda',
    answering: 'Javob bermoqda',
    finished: 'Yakunlandi',
    expired: 'Vaqti tugadi',
  } as Record<string, string>,
  groups: {
    junior: 'Kichik (1–4)',
    middle: 'O‘rta (5–8)',
    senior: 'Katta (9–11)',
  } as Record<string, string>,

  // Reyting va kartalar
  ratingTitle: 'Reyting',
  monthTab: 'Oylik',
  totalTab: 'Umumiy',
  allGroups: 'Barcha guruhlar',
  colRank: 'O‘rin',
  noRating: 'Hali natija yo‘q',
  nominations: 'Nominatsiyalar',
  nomTopMonth: 'Oyning kitobxoni',
  nomMostSessions: 'Eng ko‘p seans',
  nomMostLetters: 'Eng ko‘p harf',
  cardsTitle: 'Kunlik kartalar',
  noCards: 'Hali karta ochilmagan',
  lockedCards: 'Ochilmagan kartalar',
  cardsHint: 'Har bir yakunlangan seansdan keyin yangi karta ochiladi',

  // Chuqur javob va tahrirlash
  deepTitle: 'Chuqur javob',
  deepHint: 'Kitobdan nimani o‘rgandingiz? 3–4 jumla yozing — o‘qituvchi o‘qib, ball qo‘yadi.',
  deepPlaceholder: 'Fikringizni yozing…',
  deepSaved: 'Saqlandi — o‘qituvchi baholaydi',
  deepGraded: 'O‘qituvchi bahosi',
  save: 'Saqlash',
  edit: 'Tahrirlash',
  colVariant: 'Variant',
  nameHint: 'Bu ism ochiq reytingda ko‘rinadi',

  // Modul kaliti (kutubxonachi paneli)
  switchTitle: 'Modul holati',
  moduleOn: 'Yoqilgan',
  moduleOff: 'O‘chirilgan',
  turnOn: 'Yoqish',
  turnOff: 'O‘chirish',
  switchHint:
    'O‘chirilganda o‘quvchilar «Белес» ga kira olmaydi. Ballar, seanslar va sertifikatlar bazada saqlanib qoladi — qayta yoqsangiz, hammasi joyida davom etadi.',
  disabledTitle: '«Белес» vaqtincha o‘chirilgan',
  disabledText:
    'Kutubxonachi modulni qayta yoqqach, o‘yin davom etadi. Yig‘ilgan ballaringiz saqlanib turibdi.',

  // Savollar boshqaruvi (kutubxonachi)
  puzzlesTitle: 'Savollar',
  puzzlesHint: 'Savollar bazadan keladi — kodga yozilmaydi. Shu yerdan qo‘shasiz.',
  books: 'Kitoblar',
  addBook: 'Yangi kitob',
  bookTitleLabel: 'Kitob nomi',
  authorLabel: 'Muallif',
  pagesLabel: 'Betlar soni',
  sizeFactorLabel: 'Hajm koeffitsienti',
  keysTotalLabel: 'Kalitlar soni',
  addBookBtn: 'Kitobni saqlash',
  selectBook: 'Kitob',
  noBooks: 'Hali kitob qo‘shilmagan. Avval kitob qo‘shing.',
  addPuzzle: 'Savol qo‘shish',
  editPuzzle: 'Savolni tahrirlash',
  kindLabel: 'Savol turi',
  fromPageLabel: 'Qaysi betdan ochiladi',
  questionLabel: 'Savol matni',
  hintLabel: 'Ipucha (ixtiyoriy)',
  letterLabel: 'Harf (ixtiyoriy)',
  positionLabel: 'Kalit tartibi',
  pointsLabel: 'Ball',
  optionsLabel: 'Variantlar',
  correctLabel: 'To‘g‘ri',
  addOption: 'Variant qo‘shish',
  answersLabel: 'Qabul qilinadigan javoblar',
  addAnswer: 'Javob qo‘shish',
  orderNote: 'Variantlarni TO‘G‘RI tartibda yozing — o‘quvchiga aralashtirib ko‘rsatiladi.',
  optionNote: 'To‘g‘ri javobning yonidagi doirachani belgilang.',
  openNote:
    'Bir nechta shaklni yozsangiz bo‘ladi. Qo‘shimchalar, kirill/lotin farqi va bitta harflik xato avtomatik kechiriladi.',
  noPuzzles: 'Bu kitob va variant uchun savol yo‘q.',
  deleteBtn: 'O‘chirish',
  cancel: 'Bekor qilish',
  confirmDelete: 'Savol o‘chirilsinmi?',
  active: 'Faol',
  kinds: {
    ORDER: 'Tartibga solish',
    FALSE_STATEMENT: 'Yolg‘on jumlani topish',
    LINK: 'Bog‘lash',
    CAUSE: 'Sabab',
    WHO_SAID: 'Kim aytdi',
    OPEN: 'Ochiq javob',
    FINAL: 'Yakuniy kalit',
  } as Record<string, string>,

  // Xatolar
  errors: {
    bad_code: 'Kod noto‘g‘ri. Kutubxonachidan tekshirib so‘rang.',
    no_daily_code: 'Bugun uchun kod hali yaratilmagan. Kutubxonachiga murojaat qiling.',
    no_book: 'O‘yinga kitob biriktirilmagan. Kutubxonachiga murojaat qiling.',
    already_played: 'Bugungi seans allaqachon o‘tkazilgan. Ertaga qaytib keling.',
    no_session: 'Seans topilmadi.',
    not_reading: 'Bu amal hozir mumkin emas.',
    still_reading: 'O‘qish vaqti hali tugamadi.',
    not_answering: 'Javob bosqichi tugagan.',
    deadline_passed: 'Javob vaqti tugadi.',
    extra_time_used: 'Qo‘shimcha vaqt allaqachon ishlatilgan.',
    no_attempts_left: 'Bu savolga urinishlar tugadi.',
    bad_page: 'Bet raqami noto‘g‘ri.',
    bad_score: 'Ball 0 dan 100 gacha bo‘lishi kerak.',
    deep_too_short: 'Javob juda qisqa — kamida bir necha jumla yozing.',
    already_graded: 'Javob baholangan, endi o‘zgartirib bo‘lmaydi.',
    bad_name: 'Ism 2–40 belgidan iborat bo‘lishi kerak.',
    not_found: 'Topilmadi.',
    module_disabled: '«Белес» vaqtincha o‘chirilgan.',
    settings_failed: 'Kalitni saqlab bo‘lmadi. beles.sql qayta ishga tushirilganini tekshiring.',
    need_question: 'Savol matnini yozing.',
    need_options: 'Kamida 2 ta variant kerak.',
    need_correct: 'To‘g‘ri javobni belgilang.',
    need_answers: 'Kamida bitta qabul qilinadigan javob yozing.',
    need_book: 'Avval kitob qo‘shing.',
    too_many_requests: 'Juda ko‘p urinish. Bir oz kuting.',
    unauthorized: 'Avval tizimga kiring.',
    forbidden: 'Ruxsat yo‘q.',
    server_error: 'Xatolik yuz berdi. Qaytadan urinib ko‘ring.',
  } as Record<string, string>,

  levels: {
    start: 'Boshlovchi',
    reader: 'Kitobxon',
    explorer: 'Izlanuvchi',
    master: 'Usta',
    champion: 'Chempion',
  } as Record<string, string>,
};

const kk: typeof uz = {
  title: 'Белес',
  subtitle: 'Кітап оқу ойыны',

  yourProgress: 'Сіздің жағдайыңыз',
  currentPage: 'Ағымдағы бет',
  currentKey: 'Кілт',
  totalScore: 'Жалпы ұпай',
  level: 'Дәреже',
  letters: 'Жиналған әріптер',
  noLetters: 'Әлі әріп жиналмаған',
  sessions: 'Сеанстар',
  book: 'Кітап',
  noBook: 'Кітап әлі бекітілмеген',
  startSession: 'Сеансты бастау',
  continueSession: 'Сеансты жалғастыру',
  todayDone: 'Бүгінгі сеанс аяқталды. Ертең күтеміз!',
  todayScore: 'Бүгінгі ұпай',

  codeTitle: 'Күнделікті код',
  codeHint: 'Кітапханашыдан бүгінгі 4 таңбалы кодты сұраңыз',
  codePlaceholder: '0000',
  start: 'Бастау',

  reading: 'Оқу уақыты',
  readingHint:
    'Телефонды қойыңыз да, кітап оқыңыз. Уақыт серверде саналады — экран өшсе де тоқтамайды.',
  warnFive: '5 минут қалды',
  extend: '+15 минут',
  extendHint: 'Қосымша уақыт ұпайды азайтпайды',
  readingOver: 'Оқу уақыты аяқталды',
  pageLabel: 'Нешінші бетте тоқтадыңыз?',
  pagePlaceholder: 'Бет нөмірі',
  toQuestions: 'Сұрақтарға өту',

  answering: 'Жауап уақыты',
  extraTime: '+3 минут',
  extraTimeHint: 'Тек бір рет беріледі',
  extraTimeUsed: 'Қосымша уақыт пайдаланылған',
  attemptsLeft: 'Талпыныс қалды',
  answer: 'Жауап беру',
  answerPlaceholder: 'Жауабыңызды жазыңыз',
  orderHint: 'Нұсқаларды дұрыс ретпен басыңыз',
  clear: 'Тазалау',
  correct: 'Дұрыс!',
  wrong: 'Қате',
  hint: 'Нұсқау',
  solved: 'Шешілді',
  closed: 'Жабылды',
  points: 'ұпай',
  newLetter: 'Жаңа әріп',
  noQuestions: 'Осы бетке дейін сұрақ қалмады. Сеанс қатысу ұпайымен аяқталды.',

  finished: 'Сеанс аяқталды',
  expired: 'Жауап уақыты бітті',
  sessionScore: 'Сеанс ұпайы',
  backHome: '«Белес» бетіне қайту',
  back: 'Артқа',
  toLibrary: 'Кітапхана',
  loading: 'Жүктелуде…',

  librarianPanel: 'Кітапханашы панелі',
  teacherPanel: 'Мұғалім панелі',
  dailyCodeTitle: 'Бүгінгі код',
  generateCode: 'Код жасау',
  codeReady: 'Оқушыларға осы кодты айтыңыз',
  noCodeYet: 'Бүгінге код әлі жасалмаған',
  attendance: 'Бүгінгі қатысу',
  noSessions: 'Бүгін әзірше ешкім сеанс бастаған жоқ',
  refresh: 'Жаңарту',
  participants: 'Қатысушылар',
  noParticipants: 'Қатысушы жоқ',
  statTotal: 'Барлық қатысушы',
  statToday: 'Бүгінгі сеанстар',
  statReading: 'Оқып жатыр',
  statAnswering: 'Жауап беріп жатыр',
  deepAnswers: 'Терең жауаптар',
  noDeepAnswers: 'Бағаланатын жауап жоқ',
  gradeBtn: 'Бағалау',
  gradedLabel: 'Бағаланған',
  scorePlaceholder: 'Ұпай (0–100)',
  finalConfirm: 'Қорытынды растау',
  confirmBtn: 'Растау',
  certificate: 'Сертификат',
  verifyCode: 'Тексеру коды',
  keysDone: 'Ашылған кілттер',
  colName: 'Аты',
  colClass: 'Сынып',
  colGroup: 'Топ',
  colStatus: 'Күйі',
  colPage: 'Бет',
  colScore: 'Ұпай',
  colTime: 'Уақыт',
  colKey: 'Кілт',
  colSessions: 'Сеанстар',
  colLevel: 'Дәреже',
  colBook: 'Кітап',
  colActions: 'Әрекет',
  phases: {
    reading: 'Оқып жатыр',
    reading_over: 'Бет нөмірін күтуде',
    answering: 'Жауап беріп жатыр',
    finished: 'Аяқталды',
    expired: 'Уақыты бітті',
  },
  groups: {
    junior: 'Кіші (1–4)',
    middle: 'Орта (5–8)',
    senior: 'Үлкен (9–11)',
  },

  ratingTitle: 'Рейтинг',
  monthTab: 'Айлық',
  totalTab: 'Жалпы',
  allGroups: 'Барлық топтар',
  colRank: 'Орын',
  noRating: 'Әзірге нәтиже жоқ',
  nominations: 'Номинациялар',
  nomTopMonth: 'Айдың оқырманы',
  nomMostSessions: 'Ең көп сеанс',
  nomMostLetters: 'Ең көп әріп',
  cardsTitle: 'Күнделікті карталар',
  noCards: 'Әзірге карта ашылмаған',
  lockedCards: 'Ашылмаған карталар',
  cardsHint: 'Әр аяқталған сеанстан кейін жаңа карта ашылады',

  deepTitle: 'Терең жауап',
  deepHint: 'Кітаптан не үйрендіңіз? 3–4 сөйлем жазыңыз — мұғалім оқып, ұпай қояды.',
  deepPlaceholder: 'Ойыңызды жазыңыз…',
  deepSaved: 'Сақталды — мұғалім бағалайды',
  deepGraded: 'Мұғалім бағасы',
  save: 'Сақтау',
  edit: 'Өңдеу',
  colVariant: 'Нұсқа',
  nameHint: 'Бұл ат ашық рейтингте көрінеді',

  switchTitle: 'Модуль күйі',
  moduleOn: 'Қосулы',
  moduleOff: 'Өшірулі',
  turnOn: 'Қосу',
  turnOff: 'Өшіру',
  switchHint:
    'Өшірілгенде оқушылар «Белес»-ке кіре алмайды. Ұпайлар, сеанстар мен сертификаттар базада сақталады — қайта қоссаңыз, бәрі орнында жалғасады.',
  disabledTitle: '«Белес» уақытша өшірілген',
  disabledText:
    'Кітапханашы модульді қайта қосқанда ойын жалғасады. Жинаған ұпайларыңыз сақталып тұр.',

  puzzlesTitle: 'Сұрақтар',
  puzzlesHint: 'Сұрақтар базадан келеді — кодқа жазылмайды. Осы жерден қосасыз.',
  books: 'Кітаптар',
  addBook: 'Жаңа кітап',
  bookTitleLabel: 'Кітап атауы',
  authorLabel: 'Автор',
  pagesLabel: 'Бет саны',
  sizeFactorLabel: 'Көлем коэффициенті',
  keysTotalLabel: 'Кілттер саны',
  addBookBtn: 'Кітапты сақтау',
  selectBook: 'Кітап',
  noBooks: 'Әзірге кітап қосылмаған. Алдымен кітап қосыңыз.',
  addPuzzle: 'Сұрақ қосу',
  editPuzzle: 'Сұрақты өңдеу',
  kindLabel: 'Сұрақ түрі',
  fromPageLabel: 'Қай беттен ашылады',
  questionLabel: 'Сұрақ мәтіні',
  hintLabel: 'Нұсқау (міндетті емес)',
  letterLabel: 'Әріп (міндетті емес)',
  positionLabel: 'Кілт реті',
  pointsLabel: 'Ұпай',
  optionsLabel: 'Нұсқалар',
  correctLabel: 'Дұрыс',
  addOption: 'Нұсқа қосу',
  answersLabel: 'Қабылданатын жауаптар',
  addAnswer: 'Жауап қосу',
  orderNote: 'Нұсқаларды ДҰРЫС ретпен жазыңыз — оқушыға араластырып көрсетіледі.',
  optionNote: 'Дұрыс жауаптың қасындағы шеңберді белгілеңіз.',
  openNote:
    'Бірнеше нұсқасын жазуға болады. Жалғаулар, кирилл/латын айырмасы және бір әріптік қате автоматты кешіріледі.',
  noPuzzles: 'Бұл кітап пен нұсқа үшін сұрақ жоқ.',
  deleteBtn: 'Өшіру',
  cancel: 'Болдырмау',
  confirmDelete: 'Сұрақ өшірілсін бе?',
  active: 'Белсенді',
  kinds: {
    ORDER: 'Ретке келтіру',
    FALSE_STATEMENT: 'Жалған сөйлемді табу',
    LINK: 'Байланыстыру',
    CAUSE: 'Себеп',
    WHO_SAID: 'Кім айтты',
    OPEN: 'Ашық жауап',
    FINAL: 'Қорытынды кілт',
  },

  errors: {
    bad_code: 'Код қате. Кітапханашыдан тексеріп сұраңыз.',
    no_daily_code: 'Бүгінге код әлі жасалмаған. Кітапханашыға айтыңыз.',
    no_book: 'Ойынға кітап бекітілмеген. Кітапханашыға айтыңыз.',
    already_played: 'Бүгінгі сеанс өтіп қойған. Ертең қайта келіңіз.',
    no_session: 'Сеанс табылмады.',
    not_reading: 'Бұл әрекет қазір мүмкін емес.',
    still_reading: 'Оқу уақыты әлі аяқталған жоқ.',
    not_answering: 'Жауап кезеңі аяқталған.',
    deadline_passed: 'Жауап уақыты бітті.',
    extra_time_used: 'Қосымша уақыт пайдаланылып қойған.',
    no_attempts_left: 'Бұл сұраққа талпыныс қалмады.',
    bad_page: 'Бет нөмірі қате.',
    bad_score: 'Ұпай 0 мен 100 аралығында болуы керек.',
    deep_too_short: 'Жауап тым қысқа — кемінде бірнеше сөйлем жазыңыз.',
    already_graded: 'Жауап бағаланған, енді өзгертуге болмайды.',
    bad_name: 'Ат 2–40 таңбадан тұруы керек.',
    not_found: 'Табылмады.',
    module_disabled: '«Белес» уақытша өшірілген.',
    settings_failed: 'Кілт сақталмады. beles.sql қайта іске қосылғанын тексеріңіз.',
    need_question: 'Сұрақ мәтінін жазыңыз.',
    need_options: 'Кемінде 2 нұсқа керек.',
    need_correct: 'Дұрыс жауапты белгілеңіз.',
    need_answers: 'Кемінде бір қабылданатын жауап жазыңыз.',
    need_book: 'Алдымен кітап қосыңыз.',
    too_many_requests: 'Тым көп талпыныс. Сәл күте тұрыңыз.',
    unauthorized: 'Алдымен жүйеге кіріңіз.',
    forbidden: 'Рұқсат жоқ.',
    server_error: 'Қате шықты. Қайта көріңіз.',
  },

  levels: {
    start: 'Бастаушы',
    reader: 'Оқырман',
    explorer: 'Ізденуші',
    master: 'Шебер',
    champion: 'Чемпион',
  },
};

export type BelesStrings = typeof uz;

export function belesStrings(locale: string): BelesStrings {
  return locale === 'kk' ? kk : uz;
}

// Server xato kodini o‘qiladigan matnga aylantiradi.
export function belesErrorText(s: BelesStrings, code: string | null | undefined): string {
  if (!code) return s.errors.server_error;
  return s.errors[code] ?? s.errors.server_error;
}
